/** Featured shipping destinations shown in the footer. */
export const FOOTER_REGIONS: { code: string; label: string }[] = [
  { code: "GH", label: "Ghana" },
  { code: "DE", label: "Deutschland" },
  { code: "US", label: "United States" },
  { code: "CH", label: "Schweiz" },
  { code: "PL", label: "Polska" },
  { code: "GR", label: "Ελλάδα" },
  { code: "FR", label: "France" },
  { code: "GB", label: "United Kingdom" },
  { code: "AT", label: "Österreich" },
  { code: "CZ", label: "Česko" },
  { code: "TR", label: "Türkiye" },
  { code: "IT", label: "Italia" },
  { code: "CA", label: "Canada" },
  { code: "BE", label: "Belgium" },
  { code: "HU", label: "Magyar" },
  { code: "CN", label: "中国" },
  { code: "NL", label: "Nederland" },
  { code: "AU", label: "Australia" },
  { code: "DK", label: "Danmark" },
  { code: "HR", label: "Hrvatska" },
  { code: "HK", label: "香港" },
  { code: "ES", label: "España" },
  { code: "MX", label: "México" },
  { code: "SE", label: "Sverige" },
  { code: "RO", label: "Romania" },
  { code: "KR", label: "대한민국" },
  { code: "PT", label: "Portugal" },
  { code: "BR", label: "Brasil" },
  { code: "AR", label: "Argentina" },
  { code: "RU", label: "Россия" },
  { code: "JP", label: "日本" },
  { code: "IN", label: "India" },
  { code: "FI", label: "Suomi" },
  { code: "NO", label: "Norge" },
  { code: "SK", label: "Slovensko" },
  { code: "TW", label: "臺灣" },
  { code: "NZ", label: "New Zealand" },
  { code: "SG", label: "Singapore" },
  { code: "AE", label: "UAE" },
  { code: "ZA", label: "South Africa" },
  { code: "CL", label: "Chile" },
  { code: "ID", label: "Indonesia" },
  { code: "MY", label: "Malaysia" },
  { code: "PH", label: "Philippines" },
  { code: "TH", label: "Thailand" },
  { code: "OM", label: "سلطنة عمان" },
  { code: "QA", label: "دولة قطر" },
  { code: "BH", label: "البحرين" },
  { code: "KW", label: "الكويت" },
  { code: "NG", label: "Nigeria" },
  { code: "KE", label: "Kenya" },
  { code: "CI", label: "Côte d'Ivoire" },
];
