export type Family = "FLORAL" | "ORIENTAL" | "WOODY" | "FRESH" | "CITRUS" | "SPICY";
export type Gender = "MENS" | "WOMENS" | "UNISEX";

export type Concentration = "EDT" | "EDP" | "PARFUM" | "EXTRAIT";

export type OilFragrance = {
  brand: string;
  brandSlug: string;
  model: string;
  reference: string;
  description: string;
  price: number;
  family: Family;
  gender: Gender;
  topNotes: string[];
  heartNotes: string[];
  baseNotes: string[];
  sillage: "SUBTLE" | "MODERATE" | "INTENSE" | "POWERFUL";
  longevity: string;
  category: string;
  featured?: boolean;
  images: string[];
  series?: string;
  concentration?: Concentration;
  collection?: string;
  year?: number;
};

const IMG = "/images/fragrances/new";

function cat(family: Family): string {
  return family.charAt(0) + family.slice(1).toLowerCase();
}

function oil(
  item: Omit<OilFragrance, "description" | "category" | "sillage" | "longevity"> &
    Partial<Pick<OilFragrance, "description" | "category" | "sillage" | "longevity">>
): OilFragrance {
  return {
    sillage: item.sillage ?? "MODERATE",
    longevity: item.longevity ?? "8-10 hours",
    category: item.category ?? cat(item.family),
    description:
      item.description ??
      `Oil-based ${item.model} by ${item.brand} - an alcohol-free perfume oil with a dab-on wooden cap. Available in 30ml, 50ml, and 100ml.`,
    ...item,
  };
}

export const catalog: OilFragrance[] = [
  oil({
    brand: "Armaf",
    brandSlug: "armaf",
    model: "Club de Nuit Intense",
    reference: "CA-EDP-CDNIM-50",
    description:
      "Oil-based Club de Nuit Intense — Armaf's smoky pineapple-and-birch signature, adapted as an alcohol-free EDP-strength perfume oil. Bright lemon and pineapple open onto birch, jasmine, and rose, then dry down to musk, ambergris, patchouli, and vanilla. Available in 30ml, 50ml, and 100ml.",
    price: 62,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Lemon", "Pineapple", "Bergamot", "Blackcurrant", "Apple"],
    heartNotes: ["Birch", "Jasmine", "Rose"],
    baseNotes: ["Musk", "Ambergris", "Patchouli", "Vanilla"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    category: "Woody",
    series: "Club de Nuit",
    concentration: "EDP",
    collection: "Club de Nuit",
    year: 2015,
    featured: true,
    images: [
      `${IMG}/oil-club-de-nuit-intense.png`,
      `${IMG}/oil-club-de-nuit-intense-parfum.png`,
      `${IMG}/oil-club-de-nuit-intense-le.png`,
      `${IMG}/oil-club-de-nuit-intense-le-2024.png`,
      `${IMG}/oil-club-de-nuit-intense-extreme.png`,
    ],
  }),
  oil({
    brand: "Davidoff",
    brandSlug: "davidoff",
    model: "Cool Water Women",
    reference: "CA-OIL-CW-W-50",
    description:
      "Oil-based Cool Water Women - a fresh aquatic floral that sits close to skin. Alcohol-free perfume oil with a cool marine opening and soft musk dry-down.",
    price: 54,
    family: "FRESH",
    gender: "WOMENS",
    topNotes: ["Pineapple", "Lotus", "Citrus zest"],
    heartNotes: ["Water lily", "Jasmine", "Rose"],
    baseNotes: ["Musk", "Sandalwood", "Cedar"],
    featured: true,
    images: [`${IMG}/oil-cool-water-women.png`],
  }),
  oil({
    brand: "Davidoff",
    brandSlug: "davidoff",
    model: "Horizon",
    reference: "CA-OIL-HOR-50",
    description:
      "Oil-based Horizon - woody aromatic inspired by open air and warm earth. An alcohol-free perfume oil for daytime wanderers.",
    price: 56,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Grapefruit", "Rosemary", "Cardamom"],
    heartNotes: ["Sage", "Juniper", "Cedar"],
    baseNotes: ["Vetiver", "Patchouli", "Amber"],
    images: [`${IMG}/oil-horizon.png`],
  }),
  oil({
    brand: "Dior",
    brandSlug: "dior",
    model: "Hypnotic Poison",
    reference: "CA-OIL-HP-50",
    description:
      "Oil-based Hypnotic Poison - bitter almond, caraway, and vanilla in a dense, alcohol-free oil. Hypnotic, warm, and lingering.",
    price: 72,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Bitter almond", "Caraway", "Apricot"],
    heartNotes: ["Jasmine", "Rose", "Lily"],
    baseNotes: ["Vanilla", "Sandalwood", "Musk"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-hypnotic-poison.png`],
  }),
  oil({
    brand: "Dior",
    brandSlug: "dior",
    model: "Miss Dior",
    reference: "CA-OIL-MD-50",
    description:
      "Oil-based Miss Dior - a sparkling floral oil of rose, peony, and patchouli. Alcohol-free couture freshness for day to evening.",
    price: 74,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Blood orange", "Pink pepper", "Bergamot"],
    heartNotes: ["Rose", "Peony", "Lily of the valley"],
    baseNotes: ["Patchouli", "Musk", "Amber"],
    images: [`${IMG}/oil-miss-dior.png`],
  }),
  oil({
    brand: "Dior",
    brandSlug: "dior",
    model: "Fahrenheit -32",
    reference: "CA-OIL-F32-50",
    description:
      "Oil-based Fahrenheit -32 - iced violet, mint, and leather woods in a concentrated perfume oil. Cooler, cleaner, alcohol-free.",
    price: 68,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Mint", "Violet leaf", "Citrus"],
    heartNotes: ["Nutmeg", "Cedar", "Lavender"],
    baseNotes: ["Leather", "Vetiver", "Musk"],
    images: [`${IMG}/oil-fahrenheit-32.png`],
  }),
  oil({
    brand: "Dior",
    brandSlug: "dior",
    model: "J'adore",
    reference: "CA-OIL-JAD-50",
    description:
      "Oil-based J'adore - luminous ylang-ylang and Damascus rose in an alcohol-free oil. Soft gold florals that bloom on skin.",
    price: 76,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Bergamot", "Pear", "Magnolia"],
    heartNotes: ["Jasmine", "Rose", "Ylang-ylang"],
    baseNotes: ["Vanilla", "Musk", "Sandalwood"],
    images: [`${IMG}/oil-jadore.png`],
  }),
  oil({
    brand: "Escada",
    brandSlug: "escada",
    model: "Cherry in the Air",
    reference: "CA-OIL-CIA-50",
    description:
      "Oil-based Cherry in the Air - juicy cherry, almond blossom, and creamy woods. A playful alcohol-free oil for warm days.",
    price: 48,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Cherry", "Lemon", "Red berries"],
    heartNotes: ["Almond blossom", "Jasmine", "Rose"],
    baseNotes: ["Vanilla", "Musk", "Sandalwood"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-cherry-in-the-air.png`],
  }),
  oil({
    brand: "Escada",
    brandSlug: "escada",
    model: "Escada Collection",
    reference: "CA-OIL-ESC-COL-50",
    description:
      "Oil-based Escada Collection - a bright fruity-floral signature oil. Alcohol-free, cheerful, and easy to wear.",
    price: 49,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Apple", "Bergamot", "Peach"],
    heartNotes: ["Rose", "Freesia", "Jasmine"],
    baseNotes: ["Musk", "Amber", "Cedar"],
    sillage: "SUBTLE",
    longevity: "6-8 hours",
    images: [`${IMG}/oil-escada-collection.png`],
  }),
  oil({
    brand: "Gucci",
    brandSlug: "gucci",
    model: "Flora",
    reference: "CA-OIL-GF-50",
    description:
      "Oil-based Gucci Flora - peony, osmanthus, and sandalwood in a garden-fresh perfume oil. Alcohol-free and luminous on skin.",
    price: 78,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Citrus", "Peony", "Pink pepper"],
    heartNotes: ["Osmanthus", "Rose", "Rangoon creeper"],
    baseNotes: ["Sandalwood", "Patchouli", "Musk"],
    featured: true,
    images: [`${IMG}/oil-gucci-flora.png`],
  }),
  oil({
    brand: "Hermès",
    brandSlug: "hermes",
    model: "Terre d'Hermès",
    reference: "CA-OIL-TDH-50",
    description:
      "Oil-based Terre d'Hermès - flint, orange, and vetiver grounded in an alcohol-free oil. Mineral earth, close and lasting.",
    price: 88,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Orange", "Grapefruit", "Flint"],
    heartNotes: ["Pepper", "Pelargonium", "Atlas cedar"],
    baseNotes: ["Vetiver", "Benzoin", "Patchouli"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-terre-dhermes.png`],
  }),
  oil({
    brand: "Hugo Boss",
    brandSlug: "hugo-boss",
    model: "Boss Man",
    reference: "CA-OIL-HBM-50",
    description:
      "Oil-based Hugo Boss Man - apple, cinnamon, and warm woods in a clean masculine perfume oil. Alcohol-free office-to-evening wear.",
    price: 52,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Apple", "Citrus", "Bergamot"],
    heartNotes: ["Cinnamon", "Geranium", "Clove"],
    baseNotes: ["Sandalwood", "Olive wood", "Vetiver"],
    images: [`${IMG}/oil-boss-man.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Tobacco Vanilla",
    reference: "CA-OIL-TV-50",
    description:
      "Oil-based Tobacco Vanilla - dried tobacco leaf, tonka, and creamy vanilla in a rich alcohol-free oil. Warm, gourmand, unforgettable.",
    price: 118,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Tobacco leaf", "Spicy notes", "Bergamot"],
    heartNotes: ["Tonka", "Cacao", "Tobacco blossom"],
    baseNotes: ["Vanilla", "Dried fruits", "Woody notes"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-tobacco-vanilla.png`],
  }),
  oil({
    brand: "Jean Paul Gaultier",
    brandSlug: "jpg",
    model: "Scandal by Night",
    reference: "CA-OIL-SBN-50",
    description:
      "Oil-based Scandal by Night - honey, gardenia, and caramel woods. A nocturnal alcohol-free oil with a bold trail.",
    price: 64,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Honey", "Gardenia", "Orange blossom"],
    heartNotes: ["Tuberose", "Jasmine", "Peach"],
    baseNotes: ["Caramel", "Sandalwood", "Patchouli"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-scandal-by-night.png`],
  }),
  oil({
    brand: "Jimmy Choo",
    brandSlug: "jimmy-choo",
    model: "Intense",
    reference: "CA-OIL-JCI-50",
    description:
      "Oil-based Jimmy Choo Intense - toffee, sweet woods, and spice in an alcohol-free perfume oil. Evening glamour, skin-close.",
    price: 62,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Blood orange", "Green notes", "Pear"],
    heartNotes: ["Rose", "Tiger orchid", "Toffee"],
    baseNotes: ["Patchouli", "Sweet woods", "Musk"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-jimmy-choo-intense.png`],
  }),
  oil({
    brand: "Maison Francis Kurkdjian",
    brandSlug: "maison-francis-kurkdjian",
    model: "Oud Satin Mood",
    reference: "CA-OIL-OSM-50",
    description:
      "Oil-based Oud Satin Mood - Bulgarian rose, oud, and violet powder in a silk-smooth perfume oil. Alcohol-free haute parfumerie.",
    price: 145,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Violet", "Benzoin", "Raspberry"],
    heartNotes: ["Bulgarian rose", "Oud", "Geranium"],
    baseNotes: ["Vanilla", "Amber", "Cashmeran"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-oud-satin-mood.png`],
  }),
  oil({
    brand: "Ralph Lauren",
    brandSlug: "ralph-lauren",
    model: "Polo Sport",
    reference: "CA-OIL-PS-50",
    description:
      "Oil-based Polo Sport - mint, melon, and clean musk in a sporty alcohol-free oil. Fresh after movement, polished at the office.",
    price: 50,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Mint", "Aldehyde", "Bergamot"],
    heartNotes: ["Melon", "Jasmine", "Geranium"],
    baseNotes: ["Musk", "Cedar", "Sandalwood"],
    sillage: "SUBTLE",
    longevity: "6-8 hours",
    images: [`${IMG}/oil-polo-sport.png`],
  }),
  oil({
    brand: "Lancôme",
    brandSlug: "lancome",
    model: "La Vie Est Belle",
    reference: "CA-OIL-LVEB-50",
    description:
      "Oil-based La Vie Est Belle - iris, praline, and patchouli in a gourmand perfume oil. Alcohol-free sweetness with a velvet trail.",
    price: 70,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Blackcurrant", "Pear", "Bergamot"],
    heartNotes: ["Iris", "Jasmine", "Orange blossom"],
    baseNotes: ["Praline", "Vanilla", "Patchouli"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-la-vie-est-belle.png`],
  }),
  oil({
    brand: "Le Labo",
    brandSlug: "le-labo",
    model: "Santal 33",
    reference: "CA-OIL-S33-50",
    description:
      "Oil-based Santal 33 - Australian sandalwood, papyrus, and leather iris in an alcohol-free oil. The cult woody signature, closer to skin.",
    price: 128,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Violet", "Cardamom", "Papyrus"],
    heartNotes: ["Iris", "Ambrox", "Cedar"],
    baseNotes: ["Sandalwood", "Leather", "Musk"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-santal-33.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "Ombre Nomade",
    reference: "CA-OIL-ON-50",
    description:
      "Oil-based Ombre Nomade - smoky oud, raspberry, and incense in a desert-night perfume oil. Alcohol-free, powerful, and enveloping.",
    price: 165,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Raspberry", "Saffron", "Bergamot"],
    heartNotes: ["Rose", "Incense", "Geranium"],
    baseNotes: ["Oud", "Benzoin", "Amber"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-ombre-nomade.png`],
  }),
  oil({
    brand: "Mancera",
    brandSlug: "mancera",
    model: "Red Tobacco",
    reference: "CA-OIL-RT-50",
    description:
      "Oil-based Red Tobacco - cinnamon, tobacco, and vanilla incense in a dense alcohol-free oil. Warm spice with a long, smoky trail.",
    price: 92,
    family: "SPICY",
    gender: "UNISEX",
    topNotes: ["Cinnamon", "Incense", "Nutmeg"],
    heartNotes: ["Tobacco", "Patchouli", "Jasmine"],
    baseNotes: ["Vanilla", "Amber", "White musk"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-red-tobacco.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "Afternoon Swim",
    reference: "CA-OIL-AS-50",
    description:
      "Oil-based Afternoon Swim - sunlit orange, bergamot, and sea musk in a citrus perfume oil. Alcohol-free sparkle that lasts past noon.",
    price: 155,
    family: "CITRUS",
    gender: "UNISEX",
    topNotes: ["Orange", "Bergamot", "Mandarin"],
    heartNotes: ["Grapefruit", "Neroli", "Petitgrain"],
    baseNotes: ["Musk", "Ambergris", "Driftwood"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-afternoon-swim.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "Météore",
    reference: "CA-OIL-MET-50",
    description:
      "Oil-based Météore - pink pepper, mandarin, and cedar in a bright aromatic oil. Alcohol-free energy with a polished dry-down.",
    price: 155,
    family: "SPICY",
    gender: "UNISEX",
    topNotes: ["Pink pepper", "Mandarin", "Bergamot"],
    heartNotes: ["Juniper", "Geranium", "Clary sage"],
    baseNotes: ["Cedar", "Vetiver", "Musk"],
    images: [`${IMG}/oil-meteore.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "L'Immensité",
    reference: "CA-OIL-LIM-50",
    description:
      "Oil-based L'Immensité - ginger, grapefruit, and amber woods in an alcohol-free oil. Vast, clean, and quietly powerful.",
    price: 158,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Grapefruit", "Ginger", "Bergamot"],
    heartNotes: ["Rosemary", "Sage", "Water notes"],
    baseNotes: ["Amberwood", "Labdanum", "Musk"],
    images: [`${IMG}/oil-limmensite.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "Imagination",
    reference: "CA-OIL-IMG-50",
    description:
      "Oil-based Imagination - black tea, ambrox, and citrus in a luminous perfume oil. Alcohol-free clarity that lasts all day.",
    price: 158,
    family: "FRESH",
    gender: "UNISEX",
    topNotes: ["Citron", "Calabrian bergamot", "Neroli"],
    heartNotes: ["Black tea", "Tunisian orange blossom", "Ginger"],
    baseNotes: ["Ambrox", "Guaiac wood", "Olibanum"],
    featured: true,
    images: [`${IMG}/oil-imagination.png`],
  }),
  oil({
    brand: "Marc Jacobs",
    brandSlug: "marc-jacobs",
    model: "Decadence",
    reference: "CA-OIL-DEC-50",
    description:
      "Oil-based Decadence - plum, iris, and suede woods in an alcohol-free oil. Luxe, dark, and velvety on skin.",
    price: 66,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Plum", "Saffron", "Iris"],
    heartNotes: ["Rose", "Jasmine", "Orris"],
    baseNotes: ["Vetiver", "Papyrus", "Amber"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-decadence.png`],
  }),
  oil({
    brand: "Paco Rabanne",
    brandSlug: "paco-rabanne",
    model: "Olympéa",
    reference: "CA-OIL-OLY-50",
    description:
      "Oil-based Olympéa - salted vanilla, jasmine, and ambergris in a sun-warmed perfume oil. Alcohol-free goddess trail.",
    price: 58,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Green mandarin", "Water jasmine", "Ginger lily"],
    heartNotes: ["Salted vanilla", "Orange blossom", "Jasmine"],
    baseNotes: ["Ambergris", "Cashmere wood", "Sandalwood"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-olympea.png`],
  }),
  oil({
    brand: "Ralph Lauren",
    brandSlug: "ralph-lauren",
    model: "Polo Blue",
    reference: "CA-OIL-PB-50",
    description:
      "Oil-based Polo Blue - cucumber, melon, and suede musk in a cool aquatic perfume oil. Alcohol-free freshness with lasting wear.",
    price: 52,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Melon", "Cucumber", "Mandarin"],
    heartNotes: ["Basil", "Sage", "Geranium"],
    baseNotes: ["Suede", "Musk", "Woods"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-polo-blue.png`],
  }),

  // --- inventory oils not previously seeded ---
  oil({
    brand: "Cosy Aura",
    brandSlug: "cosy-aura",
    model: "Sugar Baby",
    reference: "CA-OIL-SB-50",
    price: 42,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Cotton candy", "Bergamot", "Pink pepper"],
    heartNotes: ["Jasmine", "Vanilla orchid", "Peach"],
    baseNotes: ["Sugar", "Musk", "Sandalwood"],
    images: [`${IMG}/oil-sugar-baby.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Oud Wood",
    reference: "CA-OIL-OW-50",
    price: 125,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Rosewood", "Cardamom", "Chinese pepper"],
    heartNotes: ["Oud", "Sandalwood", "Vetiver"],
    baseNotes: ["Tonka", "Amber", "Vanilla"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-oud-wood.png`],
  }),
  oil({
    brand: "Creed",
    brandSlug: "creed",
    model: "Aventus",
    reference: "CA-OIL-AV-50",
    price: 135,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Pineapple", "Bergamot", "Blackcurrant", "Apple"],
    heartNotes: ["Birch", "Patchouli", "Jasmine", "Rose"],
    baseNotes: ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-aventus.png`],
  }),
  oil({
    brand: "Dior",
    brandSlug: "dior",
    model: "Sauvage",
    reference: "CA-OIL-SAU-50",
    price: 72,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Calabrian bergamot", "Pepper"],
    heartNotes: ["Sichuan pepper", "Lavender", "Pink pepper", "Vetiver"],
    baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
    sillage: "INTENSE",
    featured: true,
    images: [`${IMG}/oil-sauvage.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Grey Vetiver",
    reference: "CA-OIL-GV-50",
    price: 112,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Grapefruit", "Orange blossom", "Sage"],
    heartNotes: ["Vetiver", "Orris", "Nutmeg"],
    baseNotes: ["Oakmoss", "Amberwood", "Woods"],
    images: [`${IMG}/oil-grey-vetiver.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Vanilla Sex",
    reference: "CA-OIL-VSX-50",
    price: 122,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Vanilla", "Bergamot", "Pink pepper"],
    heartNotes: ["Tuberose", "Jasmine", "Tonka"],
    baseNotes: ["Benzoin", "Sandalwood", "Musk"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-vanilla-sex.png`],
  }),
  oil({
    brand: "Yves Saint Laurent",
    brandSlug: "ysl",
    model: "Black Opium",
    reference: "CA-OIL-BO-50",
    price: 68,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Pink pepper", "Orange blossom", "Pear"],
    heartNotes: ["Coffee", "Jasmine", "Bitter almond"],
    baseNotes: ["Vanilla", "Patchouli", "Cedar"],
    sillage: "INTENSE",
    featured: true,
    images: [`${IMG}/oil-black-opium.png`],
  }),
  oil({
    brand: "Mancera",
    brandSlug: "mancera",
    model: "Coco Vanille",
    reference: "CA-OIL-CV-50",
    price: 88,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Coconut", "Lemon", "Litsea cubeba"],
    heartNotes: ["Jasmine", "White flowers", "Ylang-ylang"],
    baseNotes: ["Vanilla", "White musk", "Sandalwood"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-coco-vanille.png`],
  }),
  oil({
    brand: "Victoria's Secret",
    brandSlug: "victorias-secret",
    model: "Love Spell",
    reference: "CA-OIL-LS-50",
    price: 44,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Cherry blossom", "Peach", "Apple"],
    heartNotes: ["White flowers", "Lily", "Freesia"],
    baseNotes: ["Musk", "Cedar", "Soft woods"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-love-spell.png`],
  }),
  oil({
    brand: "Victoria's Secret",
    brandSlug: "victorias-secret",
    model: "Intense",
    reference: "CA-OIL-VSI-50",
    price: 46,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Red berries", "Bergamot", "Pink pepper"],
    heartNotes: ["Rose", "Jasmine", "Orchid"],
    baseNotes: ["Vanilla", "Musk", "Amber"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-vs-intense.png`],
  }),
  oil({
    brand: "Victoria's Secret",
    brandSlug: "victorias-secret",
    model: "Coconut Passion Noir",
    reference: "CA-OIL-CPN-50",
    price: 45,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Coconut", "Passionfruit", "Bergamot"],
    heartNotes: ["Tiare", "Jasmine", "Orange blossom"],
    baseNotes: ["Vanilla", "Tonka", "Musk"],
    images: [`${IMG}/oil-coconut-passion-noir.png`],
  }),
  oil({
    brand: "Yves Saint Laurent",
    brandSlug: "ysl",
    model: "Black Opium Over Red",
    reference: "CA-OIL-BOOR-50",
    price: 72,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Red berries", "Pink pepper", "Bergamot"],
    heartNotes: ["Coffee", "Cherry", "Jasmine"],
    baseNotes: ["Vanilla", "Patchouli", "Amber"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-black-opium-over-red.png`],
  }),
  oil({
    brand: "Ex Nihilo",
    brandSlug: "ex-nihilo",
    model: "Blue Talisman",
    reference: "CA-OIL-BT-50",
    price: 148,
    family: "FRESH",
    gender: "UNISEX",
    topNotes: ["Red apple", "Bergamot", "Pink pepper"],
    heartNotes: ["Orange blossom", "Jasmine", "Mate"],
    baseNotes: ["Musk", "Ambergris", "Woods"],
    sillage: "INTENSE",
    featured: true,
    images: [`${IMG}/oil-blue-talisman.png`],
  }),
  oil({
    brand: "Hugo Boss",
    brandSlug: "hugo-boss",
    model: "The Scent Elixir",
    reference: "CA-OIL-TSE-50",
    price: 62,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Ginger", "Maninka fruit", "Bergamot"],
    heartNotes: ["Lavender", "Geranium", "Cinnamon"],
    baseNotes: ["Leather", "Vanilla", "Woody notes"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-the-scent-elixir.png`],
  }),
  oil({
    brand: "Burberry",
    brandSlug: "burberry",
    model: "Goddess",
    reference: "CA-OIL-BG-50",
    price: 68,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Lavender", "Cacao", "Ginger"],
    heartNotes: ["Vanilla", "Lavender absolute", "Cacao husk"],
    baseNotes: ["Vanilla caviar", "Musk", "Woods"],
    sillage: "INTENSE",
    featured: true,
    images: [`${IMG}/oil-goddess.png`],
  }),
  oil({
    brand: "Cosy Aura",
    brandSlug: "cosy-aura",
    model: "Musk Blue Berry",
    reference: "CA-OIL-MBB-50",
    price: 42,
    family: "FLORAL",
    gender: "UNISEX",
    topNotes: ["Blueberry", "Bergamot", "Red berries"],
    heartNotes: ["White musk", "Rose", "Violet"],
    baseNotes: ["Soft musk", "Vanilla", "Cedar"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-musk-blue-berry.png`],
  }),
  oil({
    brand: "Kayali",
    brandSlug: "kayali",
    model: "Oudgasm Vanilla Oud 36",
    reference: "CA-OIL-KVO-50",
    price: 98,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Vanilla", "Saffron", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Jasmine"],
    baseNotes: ["Amber", "Musk", "Sandalwood"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-oudgasm-vanilla-oud-36.png`],
  }),
  oil({
    brand: "Maison Margiela",
    brandSlug: "maison-margiela",
    model: "By the Fireplace",
    reference: "CA-OIL-BTF-50",
    price: 82,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Pink pepper", "Orange blossom", "Clove"],
    heartNotes: ["Chestnut", "Guaiac wood", "Juniper"],
    baseNotes: ["Vanilla", "Cashmeran", "Peru balsam"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    featured: true,
    images: [`${IMG}/oil-by-the-fireplace.png`],
  }),
  oil({
    brand: "Louis Vuitton",
    brandSlug: "louis-vuitton",
    model: "Spell On You",
    reference: "CA-OIL-SOY-50",
    price: 158,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Raspberry", "Rose", "Pink pepper"],
    heartNotes: ["Rose essence", "Orange blossom", "Jasmine"],
    baseNotes: ["Musk", "Woody notes", "Amber"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-spell-on-you.png`],
  }),
  oil({
    brand: "Lancôme",
    brandSlug: "lancome",
    model: "La Vie Est Belle L'Extrait",
    reference: "CA-OIL-LVEBX-50",
    price: 84,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Iris", "Pear", "Bergamot"],
    heartNotes: ["Jasmine sambac", "Orange blossom", "Patchouli"],
    baseNotes: ["Vanilla", "Tonka", "Praline"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-lveb-extrait.png`],
  }),
  oil({
    brand: "Victoria's Secret",
    brandSlug: "victorias-secret",
    model: "Bare Rose",
    reference: "CA-OIL-BR-50",
    price: 44,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Rose", "Bergamot", "Pink pepper"],
    heartNotes: ["Peony", "Lily", "Freesia"],
    baseNotes: ["Musk", "Cedar", "Soft amber"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-bare-rose.png`],
  }),
  oil({
    brand: "Nina Ricci",
    brandSlug: "nina-ricci",
    model: "Nina",
    reference: "CA-OIL-NR-50",
    price: 48,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Lemon", "Lime", "Apple"],
    heartNotes: ["Peony", "Datura", "Apple blossom"],
    baseNotes: ["Apple tree wood", "Musk", "Cedar"],
    images: [`${IMG}/oil-nina.png`],
  }),
  oil({
    brand: "Gucci",
    brandSlug: "gucci",
    model: "Guilty Elixir Pour Homme",
    reference: "CA-OIL-GGE-50",
    price: 86,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Bergamot", "Lavender", "Pink pepper"],
    heartNotes: ["Orange blossom", "Geranium", "Cinnamon"],
    baseNotes: ["Vanilla", "Patchouli", "Amberwood"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-guilty-elixir.png`],
  }),
  oil({
    brand: "Creed",
    brandSlug: "creed",
    model: "Aventus Absolu",
    reference: "CA-OIL-AVA-50",
    price: 148,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Pineapple", "Bergamot", "Ginger", "Blackcurrant"],
    heartNotes: ["Patchouli", "Birch", "Jasmine"],
    baseNotes: ["Vanilla", "Musk", "Sandalwood", "Ambergris"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-aventus-absolu.png`],
  }),
  oil({
    brand: "Maison Crivelli",
    brandSlug: "maison-crivelli",
    model: "Oud Maracuja",
    reference: "CA-OIL-OM-50",
    price: 152,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Passionfruit", "Saffron", "Bergamot"],
    heartNotes: ["Oud", "Rose", "Jasmine"],
    baseNotes: ["Vanilla", "Akigalawood", "Musk"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-oud-maracuja.png`],
  }),
  oil({
    brand: "Immortals",
    brandSlug: "immortals",
    model: "Gold Immortals",
    reference: "CA-OIL-GI-50",
    price: 96,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Saffron", "Bergamot", "Pink pepper"],
    heartNotes: ["Oud", "Rose", "Incense"],
    baseNotes: ["Amber", "Vanilla", "Musk"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-gold-immortals.png`],
  }),
  oil({
    brand: "Abdul Samad Al Qurashi",
    brandSlug: "asq",
    model: "Rouh Al Oud",
    reference: "CA-OIL-RAO-50",
    price: 118,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Saffron", "Rose", "Bergamot"],
    heartNotes: ["Oud", "Incense", "Amber"],
    baseNotes: ["Sandalwood", "Musk", "Leather"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-rouh-al-oud.png`],
  }),
  oil({
    brand: "Acqua di Parma",
    brandSlug: "acqua-di-parma",
    model: "Colonia Intensa Oud",
    reference: "CA-OIL-CIO-50",
    price: 98,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Bergamot", "Grapefruit", "Cardamom"],
    heartNotes: ["Oud", "Cedar", "Patchouli"],
    baseNotes: ["Leather", "Amber", "Musk"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-colonia-intensa-oud.png`],
  }),
  oil({
    brand: "Amouage",
    brandSlug: "amouage",
    model: "Gold Woman",
    reference: "CA-OIL-AGW-50",
    price: 142,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Frankincense", "Rose", "Lily"],
    heartNotes: ["Jasmine", "Orris", "Myrrh"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-amouage-gold.png`],
  }),
  oil({
    brand: "Amouage",
    brandSlug: "amouage",
    model: "Reflection Man",
    reference: "CA-OIL-ARM-50",
    price: 138,
    family: "FLORAL",
    gender: "MENS",
    topNotes: ["Rosemary", "Pink pepper", "Petitgrain"],
    heartNotes: ["Jasmine", "Neroli", "Orris"],
    baseNotes: ["Sandalwood", "Cedar", "Musk"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-reflection.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Tuscan Leather",
    reference: "CA-OIL-TL-50",
    price: 128,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Raspberry", "Saffron", "Thyme"],
    heartNotes: ["Leather", "Olibanum", "Jasmine"],
    baseNotes: ["Suede", "Amber", "Woody notes"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-tuscan-leather.png`],
  }),
  oil({
    brand: "Amouage",
    brandSlug: "amouage",
    model: "Opus V",
    reference: "CA-OIL-AOV-50",
    price: 155,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Rose", "Saffron", "Bergamot"],
    heartNotes: ["Oud", "Sandalwood", "Patchouli"],
    baseNotes: ["Amber", "Musk", "Incense"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-opus-v.png`],
  }),
  oil({
    brand: "Amouage",
    brandSlug: "amouage",
    model: "Interlude Black Iris",
    reference: "CA-OIL-IBI-50",
    price: 152,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Bergamot", "Orris", "Rosemary"],
    heartNotes: ["Amber", "Myrrh", "Frankincense"],
    baseNotes: ["Leather", "Oud", "Patchouli"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-interlude-black-iris.png`],
  }),
  oil({
    brand: "Shay",
    brandSlug: "shay",
    model: "Shay Oud",
    reference: "CA-OIL-SO-50",
    price: 78,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Saffron", "Rose", "Bergamot"],
    heartNotes: ["Oud", "Amber", "Incense"],
    baseNotes: ["Musk", "Sandalwood", "Leather"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-shay-oud.png`],
  }),
  oil({
    brand: "Hugo Boss",
    brandSlug: "hugo-boss",
    model: "Boss Orange",
    reference: "CA-OIL-BOR-50",
    price: 48,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Orange", "Apple", "Bergamot"],
    heartNotes: ["Maninka", "Freesia", "Spices"],
    baseNotes: ["Vanilla", "Woods", "Musk"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-boss-orange.png`],
  }),
  oil({
    brand: "Arabian Oud",
    brandSlug: "arabian-oud",
    model: "Resala",
    reference: "CA-OIL-RES-50",
    price: 108,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Rose", "Saffron", "Bergamot"],
    heartNotes: ["Oud", "Jasmine", "Amber"],
    baseNotes: ["Musk", "Sandalwood", "Vanilla"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-resala.png`],
  }),
  oil({
    brand: "Arabian Oud",
    brandSlug: "arabian-oud",
    model: "Lamsa",
    reference: "CA-OIL-LAM-50",
    price: 108,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Rose", "Saffron", "Spice"],
    heartNotes: ["Oud", "Amber", "Incense"],
    baseNotes: ["Musk", "Sandalwood", "Leather"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-lamsa.png`],
  }),
  oil({
    brand: "Cosy Aura",
    brandSlug: "cosy-aura",
    model: "Vanilla",
    reference: "CA-OIL-VAN-50",
    price: 40,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Vanilla bean", "Bergamot", "Sugar"],
    heartNotes: ["Tonka", "Heliotrope", "Cream"],
    baseNotes: ["Vanilla absolute", "Musk", "Sandalwood"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-vanilla.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Stronger With You Oud",
    reference: "CA-OIL-SWYO-50",
    price: 78,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Cardamom", "Pink pepper", "Violet"],
    heartNotes: ["Oud", "Sage", "Lavender"],
    baseNotes: ["Vanilla", "Chestnut", "Amber"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-swy-oud.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Acqua di Gio",
    reference: "CA-OIL-ADG-50",
    price: 58,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Bergamot", "Neroli", "Green tangerine"],
    heartNotes: ["Sea notes", "Jasmine", "Rosemary"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    images: [`${IMG}/oil-acqua-di-gio.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Code",
    reference: "CA-OIL-AC-50",
    price: 58,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Lemon", "Bergamot", "Star anise"],
    heartNotes: ["Olive blossom", "Guaiac wood", "Anise"],
    baseNotes: ["Tonka", "Leather", "Tobacco"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-armani-code.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Sì",
    reference: "CA-OIL-SI-50",
    price: 64,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Blackcurrant", "Mandarin", "Bergamot"],
    heartNotes: ["Rose de Mai", "Freesia", "Neroli"],
    baseNotes: ["Vanilla", "Patchouli", "Woody notes"],
    images: [`${IMG}/oil-si.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Sì Intense",
    reference: "CA-OIL-SII-50",
    price: 68,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Blackcurrant", "Mandarin", "Bergamot"],
    heartNotes: ["Rose", "Orris", "Davana"],
    baseNotes: ["Vanilla", "Patchouli", "Benzoin"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-si-intense.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Vétiver d'Hiver",
    reference: "CA-OIL-VDH-50",
    price: 88,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Bergamot", "Elemi", "Pepper"],
    heartNotes: ["Vetiver", "Cedar", "Lavender"],
    baseNotes: ["Musk", "Amber", "Woods"],
    images: [`${IMG}/oil-vetiver-dhiver.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Ocean di Gioia",
    reference: "CA-OIL-ODG-50",
    price: 58,
    family: "FRESH",
    gender: "WOMENS",
    topNotes: ["Sea notes", "Pear", "Bergamot"],
    heartNotes: ["Water lily", "Jasmine", "Rose"],
    baseNotes: ["Cedar", "Musk", "Amber"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-ocean-di-gioia.png`],
  }),
  oil({
    brand: "Giorgio Armani",
    brandSlug: "giorgio-armani",
    model: "Stronger With You Absolutely",
    reference: "CA-OIL-SWYA-50",
    price: 78,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Cardamom", "Chestnut", "Pink pepper"],
    heartNotes: ["Lavender", "Sage", "Vanilla"],
    baseNotes: ["Tonka", "Amber", "Woody notes"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-swy-absolutely.png`],
  }),
  oil({
    brand: "Atkinsons",
    brandSlug: "atkinsons",
    model: "Oud Save The King",
    reference: "CA-OIL-OSTK-50",
    price: 118,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Juniper", "Cypress", "Bergamot"],
    heartNotes: ["Oud", "Cedar", "Geranium"],
    baseNotes: ["Leather", "Amber", "Musk"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-oud-save-the-king.png`],
  }),
  oil({
    brand: "Atkinsons",
    brandSlug: "atkinsons",
    model: "Oud Save The Queen",
    reference: "CA-OIL-OSTQ-50",
    price: 118,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Rose", "Saffron", "Bergamot"],
    heartNotes: ["Oud", "Jasmine", "Incense"],
    baseNotes: ["Amber", "Musk", "Sandalwood"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-oud-save-the-queen.png`],
  }),
  oil({
    brand: "Azzaro",
    brandSlug: "azzaro",
    model: "The Most Wanted",
    reference: "CA-OIL-TMW-50",
    price: 58,
    family: "ORIENTAL",
    gender: "MENS",
    topNotes: ["Cardamom", "Ginger", "Lavender"],
    heartNotes: ["Toffee", "Redwood", "Geranium"],
    baseNotes: ["Vanilla", "Amberwood", "Musk"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-the-most-wanted.png`],
  }),
  oil({
    brand: "Azzaro",
    brandSlug: "azzaro",
    model: "Visit",
    reference: "CA-OIL-AVIS-50",
    price: 48,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Bergamot", "Cardamom", "Lavender"],
    heartNotes: ["Cedar", "Vetiver", "Geranium"],
    baseNotes: ["Musk", "Amber", "Woods"],
    images: [`${IMG}/oil-visit.png`],
  }),
  oil({
    brand: "Victoria's Secret",
    brandSlug: "victorias-secret",
    model: "Pink Chiffon",
    reference: "CA-OIL-PC-50",
    price: 44,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Bergamot", "Red berries", "Pear"],
    heartNotes: ["Chiffon flower", "Jasmine", "Peony"],
    baseNotes: ["Musk", "Vanilla", "Sandalwood"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-pink-chiffon.png`],
  }),
  oil({
    brand: "Beyoncé",
    brandSlug: "beyonce",
    model: "Heat Seduction",
    reference: "CA-OIL-HS-50",
    price: 46,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Red berries", "Mandarin", "Pink pepper"],
    heartNotes: ["Jasmine", "Peony", "Orchid"],
    baseNotes: ["Vanilla", "Musk", "Amber"],
    images: [`${IMG}/oil-heat-seduction.png`],
  }),
  oil({
    brand: "Byredo",
    brandSlug: "byredo",
    model: "Oud Immortel",
    reference: "CA-OIL-OI-50",
    price: 132,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Limoncello", "Incense", "Cardamom"],
    heartNotes: ["Oud", "Patchouli", "Papyrus"],
    baseNotes: ["Tobacco", "Moss", "Brazilwood"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-oud-immortel.png`],
  }),
  oil({
    brand: "Calvin Klein",
    brandSlug: "calvin-klein",
    model: "CK One",
    reference: "CA-OIL-CK1-50",
    price: 42,
    family: "CITRUS",
    gender: "UNISEX",
    topNotes: ["Pineapple", "Mandarin", "Papaya", "Bergamot"],
    heartNotes: ["Nutmeg", "Violet", "Rose", "Jasmine"],
    baseNotes: ["Musk", "Cedar", "Amber", "Oakmoss"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-ck-one.png`],
  }),
  oil({
    brand: "Chanel",
    brandSlug: "chanel",
    model: "Coco Mademoiselle",
    reference: "CA-OIL-CM-50",
    price: 88,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Orange", "Bergamot", "Orange blossom"],
    heartNotes: ["Rose", "Jasmine", "Litchi"],
    baseNotes: ["Patchouli", "Vetiver", "Vanilla", "Musk"],
    sillage: "INTENSE",
    featured: true,
    images: [`${IMG}/oil-coco-mademoiselle.png`],
  }),
  oil({
    brand: "Clive Christian",
    brandSlug: "clive-christian",
    model: "No.1 Gold",
    reference: "CA-OIL-CC1-50",
    price: 165,
    family: "FLORAL",
    gender: "UNISEX",
    topNotes: ["Bergamot", "Mandarin", "Cardamom"],
    heartNotes: ["Jasmine", "Ylang-ylang", "Rose"],
    baseNotes: ["Vanilla", "Sandalwood", "Ambergris"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-clive-christian-gold.png`],
  }),
  oil({
    brand: "Creed",
    brandSlug: "creed",
    model: "Royal Princess Oud",
    reference: "CA-OIL-RPO-50",
    price: 148,
    family: "ORIENTAL",
    gender: "WOMENS",
    topNotes: ["Apple", "Pink pepper", "Bergamot"],
    heartNotes: ["Rose", "Oud", "Jasmine"],
    baseNotes: ["Sandalwood", "Musk", "Amber"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-royal-princess-oud.png`],
  }),
  oil({
    brand: "Creed",
    brandSlug: "creed",
    model: "Aventus for Her",
    reference: "CA-OIL-AVH-50",
    price: 138,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Green apple", "Pink pepper", "Bergamot", "Lemon"],
    heartNotes: ["Rose", "Lilac", "Ylang-ylang"],
    baseNotes: ["Sandalwood", "Patchouli", "Musk"],
    sillage: "INTENSE",
    images: [`${IMG}/oil-aventus-for-her.png`],
  }),
  oil({
    brand: "Creed",
    brandSlug: "creed",
    model: "Royal Oud",
    reference: "CA-OIL-RO-50",
    price: 148,
    family: "WOODY",
    gender: "UNISEX",
    topNotes: ["Lemon", "Pink pepper", "Galbanum"],
    heartNotes: ["Cedar", "Angelica", "Oud"],
    baseNotes: ["Sandalwood", "Musk", "Tonka"],
    sillage: "INTENSE",
    longevity: "10-12 hours",
    images: [`${IMG}/oil-royal-oud.png`],
  }),
  oil({
    brand: "Cristiano Ronaldo",
    brandSlug: "cristiano-ronaldo",
    model: "Legacy",
    reference: "CA-OIL-CR7-50",
    price: 48,
    family: "WOODY",
    gender: "MENS",
    topNotes: ["Bergamot", "Lavender", "Cardamom"],
    heartNotes: ["Geranium", "Cedar", "Violet"],
    baseNotes: ["Musk", "Amber", "Woods"],
    images: [`${IMG}/oil-cr7-legacy.png`],
  }),
  oil({
    brand: "Davidoff",
    brandSlug: "davidoff",
    model: "Cool Water Man",
    reference: "CA-OIL-CW-M-50",
    price: 52,
    family: "FRESH",
    gender: "MENS",
    topNotes: ["Mint", "Lavender", "Coriander", "Rosemary"],
    heartNotes: ["Sandalwood", "Neroli", "Geranium"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    images: [`${IMG}/oil-cool-water-man.png`],
  }),
  oil({
    brand: "Tom Ford",
    brandSlug: "tom-ford",
    model: "Black Orchid",
    reference: "CA-OIL-BORC-50",
    price: 118,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Black truffle", "Ylang-ylang", "Bergamot", "Blackcurrant"],
    heartNotes: ["Orchid", "Spices", "Lotus", "Fruity notes"],
    baseNotes: ["Patchouli", "Vanilla", "Incense", "Sandalwood"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    featured: true,
    images: [`${IMG}/oil-black-orchid.png`],
  }),
  oil({
    brand: "Montale",
    brandSlug: "montale",
    model: "Arabians Tonka",
    reference: "CA-OIL-AT-50",
    price: 92,
    family: "ORIENTAL",
    gender: "UNISEX",
    topNotes: ["Bergamot", "Saffron", "Rose"],
    heartNotes: ["Oud", "Tonka", "Amber"],
    baseNotes: ["Vanilla", "Musk", "Woods"],
    sillage: "POWERFUL",
    longevity: "12+ hours",
    images: [`${IMG}/oil-arabians-tonka.png`],
  }),
  oil({
    brand: "Calvin Klein",
    brandSlug: "calvin-klein",
    model: "Escape",
    reference: "CA-OIL-ESC-50",
    price: 44,
    family: "FLORAL",
    gender: "WOMENS",
    topNotes: ["Peach", "Plum", "Bergamot", "Apple"],
    heartNotes: ["Rose", "Jasmine", "Lily", "Sandalwood"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    longevity: "6-8 hours",
    images: [`${IMG}/oil-escape.png`],
  }),
];
