-- Product cost prices + COGS journal source

ALTER TABLE "Fragrance" ADD COLUMN IF NOT EXISTS "costPriceGhs" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "unitCostGhs" DOUBLE PRECISION;

ALTER TYPE "JournalSource" ADD VALUE IF NOT EXISTS 'ORDER_COGS';
