-- Extend ProductType for jewelry and accessories catalogs
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'RING';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'BRACELET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'NECKLACE';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'BELT';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'WALLET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'BAG';
